#!/bin/bash

#
# The Loomiere Project (http://loomiere.com).
# This is software is neither free nor open-source! Read the LICENSE file!
# Copyright (C)2010 Valeriu Paloş (valeriu@palos.ro). All rights reserved!
#

# Log path.
log="/var/log/loomiere"

# Start logging.
mkdir -p "$log"
exec svlogd -tt "$log"
